### ISSUE TITLE
Any Plan for a Helix Theme? 

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [anufrievroman/whale#2]
I'm happy to take a stab at creating one, but I was curious if you have plans to add a theme for the Helix Editor

**Comment by anufrievroman** [comment]
To me, TUI programs don't necessarily require individual theming because (at least in all my TUI programs) they just use the terminal colors. So I didn't plan too much work on this front. But I know that you can also specify colors explicitly in vim or helix. So, if you like, please go ahead and create a theme, I'll be happy to accept a pull request :)

**Comment by Jonathan-Zollinger** [comment]
awesome! I'll give it a whirl! Thanks!

**Comment by anufrievroman** [comment]
Hi, I drafted a helix theme here: https://github.com/anufrievroman/whale/tree/main/helix
Looks okay to me, but I don't use helix that much, not sure if something is off.

**Comment by anufrievroman** [comment]
I assume the Helix theme is okay then :)

**Comment by Jonathan-Zollinger** [comment]
Hi there! sorry to've been AWOL for so long. I'll put this in as my theme and let you know if I run into any issues! thanks for making the theme!
